
@Library('gcb-jenkins-libraries')_
properties([disableConcurrentBuilds()])
//git參數
Map gitConfig = [
    url: "git@github.com:PolloChang/GCB-Ansible.git",
    credentialId: "32733b30-7ce7-4deb-8e0c-f57ca5603ddd",
    branch: "*/main"
]

pipeline {
   
  agent any
  
  stages {
    stage('Checkout') {
      steps {
        checkoutFromGit(gitConfig)
      }
    }
    stage('Execute Ansible') {
      steps {
        ansiblePlaybook disableHostKeyChecking: true ,credentialsId: 'd4008acd-d929-45dc-a811-8631c26555f3', inventory: 'inventories/development.yml', playbook: 'test.yml' 
      }
    }
  }
  post {
    always {
      echo 'One way or another, I have finished'
      deleteDir() /* clean up our workspace */
    }
    success {
      echo 'I succeeeded!'
    }
    unstable {
      echo 'I am unstable :/'
    }
    failure {
      echo 'I failed :('
    }
    changed {
      echo 'Things were different before...'
    }
  }
}